Category
JNU-econovation/econo-beep pull request #13
Opened 2022-07-11 15:08 UTC by j8won

close #11

2022-07-11 16:08 UTC, Kwon770 requested changes

2022-07-11 16:08 UTC, Kwon770 commented on src/Components/Class.js
> +const Text = styled.h3`
#12 PR의 h1h2h3와 div에 대한 설명 리뷰와 마찬가지로~

2022-07-11 16:08 UTC, Kwon770 commented on src/Components/Category.js
> +    <ClassBox>
Type Button들이 있는 Category UI에서 ClassBox와 Class 명명은 뭔가 어색한 것 같습니다. Class는 언어 문법에도 쓰이는 뜻이 강한 단어고요. TypeButtonBox, TypeButtons, TypeButtonHolder 등등은 어떨까요?

2022-07-11 16:08 UTC, Kwon770 commented on src/Components/Class.js
> +function Class({ to, src, text }) {
Category.js의 리뷰와 마찬가지로 명명 재검토 부탁드려요~

2022-07-11 16:08 UTC, Kwon770 commented on src/Components/Class.js
> +const Box = styled(Link)`
Link는 스타일링을 위한 컴포넌트가 아닙니다. styled.div 한 Box 컴포넌트에 스타일리을 하고 이를 감싸듯 부모로서 Link컴포넌트를 넣으면, Link의 자식인 모든 컴포넌트들은 링크로서 하이퍼링크 작동을 합니다.

2022-07-14 12:44 UTC, j8won commented on src/Components/Class.js
> +const Box = styled(Link)`
그런 경우 Link의 css: text-decoration은 어떻게 수정해야 하나요?

2022-07-16 06:26 UTC, merged