SearchBar Component
JNU-econovation/econo-beep pull request #14
Opened 2022-07-16 08:37 UTC by j8won

close #3

2022-07-16 12:15 UTC, Kwon770 requested changes

2022-07-16 12:15 UTC, Kwon770 commented on src/Components/SearchBar.js
> +  padding: 0px;
padding: 0는 디폴트 값입니다. 굳이 지칭할 필요 없습니다.

2022-07-16 12:15 UTC, Kwon770 commented on src/Components/SearchBar.js
> +  border: none;
마찬가지로 디폴트값입니다.

2022-07-16 12:15 UTC, Kwon770 commented on src/Components/SearchBar.js
> +  border-left: 2px solid gray;
55, 60줄을 통하여 디자인 명세에 더 맞게 수정하였습니다! 확인해보세요. 색깔을 Gray로 임의로 지정하였으니, 알맞은 색으로 변경하는 코드를 작성해봅시다.

2022-07-17 12:33 UTC, j8won commented on src/Components/SearchBar.js
> +  padding: 0px;
디폴트값이 아닌 것으로 보입니다.

2022-07-17 12:33 UTC, j8won commented on src/Components/SearchBar.js
> +  border: none;
마찬가지로 디폴트값이 아닌 것으로 보입니다.

2022-07-18 12:05 UTC, merged